version: '3.8'
services:
  web:
    build: .
    container_name: elearn-app
    ports:
      - "5001:5000"
    environment:
      - FLASK_ENV=development
      - PORT=5000
    volumes:
      - ./:/app
      - /app/__pycache__
    networks:
      - elearn-net

  nginx:
    image: nginx:latest
    container_name: elearn-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - web
    networks:
      - elearn-net

networks:
  elearn-net:
    driver: bridge

