apiVersion: v2
name: elearn-chart
description: A Helm chart for the E-Learning Platform
type: application
version: 0.1.0
appVersion: "1.0"
keywords:
  - elearning
  - education
  - flask
  - kubernetes
maintainers:
  - name: DevOps Team
    email: devops@elearn.local
